spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oswsdb?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
      
  security:
    oauth2:
      client:
        #OAuth 로그인 시 설정한 Application의 정보를 사용하여 AccessToken을 Authorization Server에게 발급받을 때 사용
        registration:
          kakao:
            client-id: 07deed17c6f5a400358f2e62adb0eb87
            client-secret: yvdLdxH5aNC4L7764VNfuN0XIpaLww7P
            redirect-uri: "http://localhost:5000/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: kakao
        #AccessToken을 Authorization Server에게 발급 받은 후, 해당 AccessToken으로 Resource Server의 API를 사용할 때  provider 부분의 정보를 사용하여 API 호출
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

OPENVIDU_URL: http://localhost:4443/
OPENVIDU_SECRET: MY_SECRET
 
server:
  port: 5000
  ssl:
    enabled: false
    
# 파일 저장 경로 배포할 때는 리눅스에 맞춰 변경해주자
file:
  path: C:/testfile/